### ISSUE TITLE
Vertex animation textures broken

### ISSUE THREAD

**Issue by kamindustries** [sideeffects/GameDevelopmentToolset#38] opened 2017-10-20 01:55 UTC
I'm running into issues with the vertex animation rop for rigid bodies (and possibly soft bodies). The results in Unity don't match Houdini. 

I believe the trouble started with commit https://github.com/sideeffects/GameDevelopmentToolset/commit/c335807b29ffaf7295c70a046281ce3eb4074811 which included https://github.com/sideeffects/GameDevelopmentToolset/commit/524eadb9584bcb36c8fc620d7e9ddfa1eb2ae488, which updates the RBD exporter to use COPs and adds additional bounding box parameters.

Commits before the COPs update work fine for me.

Observations about the bounding box change: I see that the new additional one is for pivots, but it's never used anywhere in the RBD shader. The results for both of them are very different from what I was getting pre-COPs update. For example, pre-COPs I was (400, -400) for BBOX MAX/MIN, and this new one I'm getting (55, -55) and (300, -300) for BBOX MIN/MAX and BBOX MIN/MAX 1, respectively.

Here's a test file made in Houdini Indie 16.0.762.
[fractureTest.zip](https://github.com/sideeffects/GameDevelopmentToolset/files/1400571/fractureTest.zip)

**Comment by Ambrosiussen** [comment] 2018-07-26 11:04
We have been updating the VAT tool quite a bit since the original post. We are also planning on doing a full overhaul in the near future.
Could you try updating to latest to see if the issue is still there?

Closing this issue, but feel free to re-open if you still notice this happening in the newer versions.

**Closed as completed by Ambrosiussen** 2018-07-26 11:04 UTC
Labels: BUG
